//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginOfertas3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_PRODUCT()
        {
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public decimal CAT_ID { get; set; }
        public string CAT_NOMBRE { get; set; }
        public decimal INTERES_USUARIO_INTE_ID { get; set; }
        public decimal SUB_PRODUCTO_SUB_ID { get; set; }
    
        public virtual INTERES_USUARIO INTERES_USUARIO { get; set; }
        public virtual SUB_PRODUCTO SUB_PRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
    }
}
