//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginOfertas3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_VENTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DETALLE_VENTA()
        {
            this.VALO_OFER = new HashSet<VALO_OFER>();
        }
    
        public decimal BOLETA_BOL_NRO { get; set; }
        public decimal DETALLE_ID { get; set; }
        public decimal OFERTA_OFER_ID { get; set; }
    
        public virtual BOLETA BOLETA { get; set; }
        public virtual OFERTA OFERTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VALO_OFER> VALO_OFER { get; set; }
    }
}
