//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginOfertas3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAVORITO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FAVORITO()
        {
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public decimal FAVO_ID { get; set; }
        public decimal OFERTA_OFER_ID { get; set; }
        public string FAVO_NOMBRE { get; set; }
    
        public virtual OFERTA OFERTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
