//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginOfertas3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERES_USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INTERES_USUARIO()
        {
            this.CAT_PRODUCT = new HashSet<CAT_PRODUCT>();
        }
    
        public decimal INTE_ID { get; set; }
        public string USUARIO_USER_ID { get; set; }
        public Nullable<decimal> INTE_1 { get; set; }
        public Nullable<decimal> INTE_2 { get; set; }
        public Nullable<decimal> INTE_3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_PRODUCT> CAT_PRODUCT { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
