//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginOfertas3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OfertasEntities : DbContext
    {
        public OfertasEntities()
            : base("name=OfertasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOLETA> BOLETA { get; set; }
        public virtual DbSet<CAT_PRODUCT> CAT_PRODUCT { get; set; }
        public virtual DbSet<COMUNA> COMUNA { get; set; }
        public virtual DbSet<CUPON> CUPON { get; set; }
        public virtual DbSet<DESCUENTO> DESCUENTO { get; set; }
        public virtual DbSet<DETALLE_VENTA> DETALLE_VENTA { get; set; }
        public virtual DbSet<DIRECCION> DIRECCION { get; set; }
        public virtual DbSet<EMPRESA> EMPRESA { get; set; }
        public virtual DbSet<FAVORITO> FAVORITO { get; set; }
        public virtual DbSet<INTERES_USUARIO> INTERES_USUARIO { get; set; }
        public virtual DbSet<OFERTA> OFERTA { get; set; }
        public virtual DbSet<PERFIL> PERFIL { get; set; }
        public virtual DbSet<PERSONA> PERSONA { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTO { get; set; }
        public virtual DbSet<PROVINCIA> PROVINCIA { get; set; }
        public virtual DbSet<REGION> REGION { get; set; }
        public virtual DbSet<RESER_ESTADO> RESER_ESTADO { get; set; }
        public virtual DbSet<RESER_OFER> RESER_OFER { get; set; }
        public virtual DbSet<SUB_PRODUCTO> SUB_PRODUCTO { get; set; }
        public virtual DbSet<TIENDA> TIENDA { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<VALO_OFER> VALO_OFER { get; set; }
    }
}
