//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginOfertas3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFERTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OFERTA()
        {
            this.DETALLE_VENTA = new HashSet<DETALLE_VENTA>();
            this.FAVORITO = new HashSet<FAVORITO>();
            this.RESER_OFER = new HashSet<RESER_OFER>();
        }
    
        public decimal PRODUCTO_PROD_ID { get; set; }
        public decimal OFER_ID { get; set; }
        public string OFER_ESTADO { get; set; }
        public decimal PORCEN_DSCTO { get; set; }
        public decimal PRECIO_DSCTO { get; set; }
        public decimal OFER_STOCK { get; set; }
        public decimal DETALLE_ID { get; set; }
        public decimal FAVO_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_VENTA> DETALLE_VENTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAVORITO> FAVORITO { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESER_OFER> RESER_OFER { get; set; }
    }
}
