//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginOfertas3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.CUPON = new HashSet<CUPON>();
            this.INTERES_USUARIO = new HashSet<INTERES_USUARIO>();
            this.RESER_OFER = new HashSet<RESER_OFER>();
            this.VALO_OFER = new HashSet<VALO_OFER>();
        }
    
        public decimal PERSONA_PERSO_ID { get; set; }
        public decimal PERSONA_PERSO_RUT { get; set; }
        public string PERSONA_PERSO_DV { get; set; }
        public string USER_ID { get; set; }
        public string USER_NOMBRE { get; set; }
        public string USER_CONTRA { get; set; }
        public decimal PERFIL_PER_ID { get; set; }
        public decimal FAVORITO_FAVO_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUPON> CUPON { get; set; }
        public virtual FAVORITO FAVORITO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INTERES_USUARIO> INTERES_USUARIO { get; set; }
        public virtual PERFIL PERFIL { get; set; }
        public virtual PERSONA PERSONA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESER_OFER> RESER_OFER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VALO_OFER> VALO_OFER { get; set; }
    }
}
