//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginOfertas3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VALO_OFER
    {
        public decimal DETALLE_VENTA_DETALLE_ID { get; set; }
        public decimal VALO_ID { get; set; }
        public decimal VALO_PUNTAJE { get; set; }
        public string USUARIO_USER_ID { get; set; }
        public System.DateTime VALO_FECHA { get; set; }
        public string VALO_COMENTARIO { get; set; }
        public string VALO_FOTO { get; set; }
    
        public virtual DETALLE_VENTA DETALLE_VENTA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
